### PR TITLE
base_time_dependent_parameter: Added security, improved get_time_dependent_parameter()

### PR DESCRIPTION
**Pull request by ghost**
Thank you for preparing this module.
I have added security.
I have improved get_time_dependent_parameter(code, date_field_name) to pass the name of the desired date field.

### CODE REVIEW

**Comment by nimarosa** [comment]
I think the changes are okay. But know i'm thinking. Should we use Date.now date if no date defined or no dict with the date_to parameter? 

Because in payroll this will work because self.dict.date_to exists, but in another modules we have two cases, the user should input the parameter containing the date, or the date itself, or we should take the Date.now date if nothing it's expecified. 

Also this will allow to show in the view the current parameter value for todays date, which can be useful for the user in some cases. 

What do you think? Feel free to add changes.

**Comment by nimarosa** [comment]
@appstogrow i tag you because i don't know if you get notification.

**Review by nimarosa — COMMENTED** [review]
Comment for this in PR comments

**Review by nimarosa — APPROVED** [review]

**Comment by ghost** [comment]
Date.now is much better 👍 I did this change now.
FYI I will be on vacation soon until almost the end of May.

**Comment by nimarosa** [comment]
Great a will merge this after a view tweaks and make the PR to oca. 

@appstogrow Do you know if I have to follow some directory structure for OCA to merge a new module? Like the readme.rst script or this is automated by cd bots?

**Pull request merged**
